// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkolaProgramiranja.Models;

#nullable disable

namespace SkolaProgramiranja.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250719135203_IzmjenaLoginView")]
    partial class IzmjenaLoginView
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("SkolaProgramiranja.Models.EvidencijaCasa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<int>("InstruktorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KursId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KursNaziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrisutniUcenici")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TemaCasa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrajanjeMin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InstruktorId");

                    b.HasIndex("KursId");

                    b.ToTable("EvidencijeCasa");
                });

            modelBuilder.Entity("SkolaProgramiranja.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Biografija")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("MoraPromijenitiLozinku")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Obrazovanje")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SlikaProfilaPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uloga")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("SkolaProgramiranja.Models.Kurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InstruktorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstruktorId");

                    b.ToTable("Kursevi");
                });

            modelBuilder.Entity("SkolaProgramiranja.Models.EvidencijaCasa", b =>
                {
                    b.HasOne("SkolaProgramiranja.Models.Korisnik", "Instruktor")
                        .WithMany()
                        .HasForeignKey("InstruktorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkolaProgramiranja.Models.Kurs", "Kurs")
                        .WithMany()
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instruktor");

                    b.Navigation("Kurs");
                });

            modelBuilder.Entity("SkolaProgramiranja.Models.Kurs", b =>
                {
                    b.HasOne("SkolaProgramiranja.Models.Korisnik", "Instruktor")
                        .WithMany("Kursevi")
                        .HasForeignKey("InstruktorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instruktor");
                });

            modelBuilder.Entity("SkolaProgramiranja.Models.Korisnik", b =>
                {
                    b.Navigation("Kursevi");
                });
#pragma warning restore 612, 618
        }
    }
}
