// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkolaProgramiranja.Models;

#nullable disable

namespace SkolaProgramiranja.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250811122812_SeedUcenici")]
    partial class SeedUcenici
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("SkolaProgramiranja.Models.EvidencijaCasa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<int>("InstruktorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KursId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KursNaziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrisutniUcenici")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TemaCasa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrajanjeMin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InstruktorId");

                    b.HasIndex("KursId");

                    b.ToTable("EvidencijeCasa");
                });

            modelBuilder.Entity("SkolaProgramiranja.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Biografija")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("MoraPromijenitiLozinku")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Obrazovanje")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SlikaProfilaPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uloga")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Email = "ucenik1@skola.com",
                            Ime = "Ucenik1",
                            Lozinka = "test123",
                            MoraPromijenitiLozinku = false,
                            Prezime = "Ucenik1",
                            SlikaProfilaPath = "profilna.png",
                            Uloga = "Ucenik"
                        },
                        new
                        {
                            Id = 102,
                            Email = "ucenik2@skola.com",
                            Ime = "Ucenik2",
                            Lozinka = "test123",
                            MoraPromijenitiLozinku = false,
                            Prezime = "Ucenik2",
                            SlikaProfilaPath = "profilna.png",
                            Uloga = "Ucenik"
                        },
                        new
                        {
                            Id = 103,
                            Email = "ucenik3@skola.com",
                            Ime = "Ucenik3",
                            Lozinka = "test123",
                            MoraPromijenitiLozinku = false,
                            Prezime = "Ucenik3",
                            SlikaProfilaPath = "profilna.png",
                            Uloga = "Ucenik"
                        },
                        new
                        {
                            Id = 104,
                            Email = "ucenik4@skola.com",
                            Ime = "Ucenik4",
                            Lozinka = "test123",
                            MoraPromijenitiLozinku = false,
                            Prezime = "Ucenik4",
                            SlikaProfilaPath = "profilna.png",
                            Uloga = "Ucenik"
                        },
                        new
                        {
                            Id = 105,
                            Email = "ucenik5@skola.com",
                            Ime = "Ucenik5",
                            Lozinka = "test123",
                            MoraPromijenitiLozinku = false,
                            Prezime = "Ucenik5",
                            SlikaProfilaPath = "profilna.png",
                            Uloga = "Ucenik"
                        },
                        new
                        {
                            Id = 106,
                            Email = "ucenik6@skola.com",
                            Ime = "Ucenik6",
                            Lozinka = "test123",
                            MoraPromijenitiLozinku = false,
                            Prezime = "Ucenik6",
                            SlikaProfilaPath = "profilna.png",
                            Uloga = "Ucenik"
                        },
                        new
                        {
                            Id = 107,
                            Email = "ucenik7@skola.com",
                            Ime = "Ucenik7",
                            Lozinka = "test123",
                            MoraPromijenitiLozinku = false,
                            Prezime = "Ucenik7",
                            SlikaProfilaPath = "profilna.png",
                            Uloga = "Ucenik"
                        },
                        new
                        {
                            Id = 108,
                            Email = "ucenik8@skola.com",
                            Ime = "Ucenik8",
                            Lozinka = "test123",
                            MoraPromijenitiLozinku = false,
                            Prezime = "Ucenik8",
                            SlikaProfilaPath = "profilna.png",
                            Uloga = "Ucenik"
                        },
                        new
                        {
                            Id = 109,
                            Email = "ucenik9@skola.com",
                            Ime = "Ucenik9",
                            Lozinka = "test123",
                            MoraPromijenitiLozinku = false,
                            Prezime = "Ucenik9",
                            SlikaProfilaPath = "profilna.png",
                            Uloga = "Ucenik"
                        },
                        new
                        {
                            Id = 110,
                            Email = "ucenik10@skola.com",
                            Ime = "Ucenik10",
                            Lozinka = "test123",
                            MoraPromijenitiLozinku = false,
                            Prezime = "Ucenik10",
                            SlikaProfilaPath = "profilna.png",
                            Uloga = "Ucenik"
                        },
                        new
                        {
                            Id = 111,
                            Email = "ucenik11@skola.com",
                            Ime = "Ucenik11",
                            Lozinka = "test123",
                            MoraPromijenitiLozinku = false,
                            Prezime = "Ucenik11",
                            SlikaProfilaPath = "profilna.png",
                            Uloga = "Ucenik"
                        },
                        new
                        {
                            Id = 112,
                            Email = "ucenik12@skola.com",
                            Ime = "Ucenik12",
                            Lozinka = "test123",
                            MoraPromijenitiLozinku = false,
                            Prezime = "Ucenik12",
                            SlikaProfilaPath = "profilna.png",
                            Uloga = "Ucenik"
                        },
                        new
                        {
                            Id = 113,
                            Email = "ucenik13@skola.com",
                            Ime = "Ucenik13",
                            Lozinka = "test123",
                            MoraPromijenitiLozinku = false,
                            Prezime = "Ucenik13",
                            SlikaProfilaPath = "profilna.png",
                            Uloga = "Ucenik"
                        },
                        new
                        {
                            Id = 114,
                            Email = "ucenik14@skola.com",
                            Ime = "Ucenik14",
                            Lozinka = "test123",
                            MoraPromijenitiLozinku = false,
                            Prezime = "Ucenik14",
                            SlikaProfilaPath = "profilna.png",
                            Uloga = "Ucenik"
                        },
                        new
                        {
                            Id = 115,
                            Email = "ucenik15@skola.com",
                            Ime = "Ucenik15",
                            Lozinka = "test123",
                            MoraPromijenitiLozinku = false,
                            Prezime = "Ucenik15",
                            SlikaProfilaPath = "profilna.png",
                            Uloga = "Ucenik"
                        },
                        new
                        {
                            Id = 116,
                            Email = "ucenik16@skola.com",
                            Ime = "Ucenik16",
                            Lozinka = "test123",
                            MoraPromijenitiLozinku = false,
                            Prezime = "Ucenik16",
                            SlikaProfilaPath = "profilna.png",
                            Uloga = "Ucenik"
                        },
                        new
                        {
                            Id = 117,
                            Email = "ucenik17@skola.com",
                            Ime = "Ucenik17",
                            Lozinka = "test123",
                            MoraPromijenitiLozinku = false,
                            Prezime = "Ucenik17",
                            SlikaProfilaPath = "profilna.png",
                            Uloga = "Ucenik"
                        },
                        new
                        {
                            Id = 118,
                            Email = "ucenik18@skola.com",
                            Ime = "Ucenik18",
                            Lozinka = "test123",
                            MoraPromijenitiLozinku = false,
                            Prezime = "Ucenik18",
                            SlikaProfilaPath = "profilna.png",
                            Uloga = "Ucenik"
                        },
                        new
                        {
                            Id = 119,
                            Email = "ucenik19@skola.com",
                            Ime = "Ucenik19",
                            Lozinka = "test123",
                            MoraPromijenitiLozinku = false,
                            Prezime = "Ucenik19",
                            SlikaProfilaPath = "profilna.png",
                            Uloga = "Ucenik"
                        },
                        new
                        {
                            Id = 120,
                            Email = "ucenik20@skola.com",
                            Ime = "Ucenik20",
                            Lozinka = "test123",
                            MoraPromijenitiLozinku = false,
                            Prezime = "Ucenik20",
                            SlikaProfilaPath = "profilna.png",
                            Uloga = "Ucenik"
                        });
                });

            modelBuilder.Entity("SkolaProgramiranja.Models.Kurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InstruktorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstruktorId");

                    b.ToTable("Kursevi");
                });

            modelBuilder.Entity("SkolaProgramiranja.Models.EvidencijaCasa", b =>
                {
                    b.HasOne("SkolaProgramiranja.Models.Korisnik", "Instruktor")
                        .WithMany()
                        .HasForeignKey("InstruktorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkolaProgramiranja.Models.Kurs", "Kurs")
                        .WithMany()
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instruktor");

                    b.Navigation("Kurs");
                });

            modelBuilder.Entity("SkolaProgramiranja.Models.Kurs", b =>
                {
                    b.HasOne("SkolaProgramiranja.Models.Korisnik", "Instruktor")
                        .WithMany("Kursevi")
                        .HasForeignKey("InstruktorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instruktor");
                });

            modelBuilder.Entity("SkolaProgramiranja.Models.Korisnik", b =>
                {
                    b.Navigation("Kursevi");
                });
#pragma warning restore 612, 618
        }
    }
}
